service: lambda-crystal-sls

custom:
  defaultAccount: dummy
  defaultDigest: dummy
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 20
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
  stage: ${opt:, self:custom.defaultStage}
  # environment:
  #   ${file(./env.yml)}

functions:
  hello:
    image:
      name: appImage
      command:
        - hello
    events:
      - http:
          path: test
          method: get
