service: serverlesshellocrystal

custom:
  defaultStage: dev
  api_version: v0
  common: common # serverless.ymlのバグ回避用

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 300
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: qazx7412

functions:
  hello_crystal:
    handler: handler.hello_crystal
    events:
      - http:
          path: test
          method: post
          integration: lambda
